- buildspec.yml
- cfn/configs/dev/us-east-1/config.yml
- cfn/templates/ecs-service.template.yml
The ECS service was failing to start up tasks because it was trying to pull images from 
`---.dkr.ecr.us-east-1.amazonaws.com/muckrock_nginx:latest` but we were tagging everything as `DEPLOYMENT_ENV-latest`. For some reason the ecs service template we generated for this repo didn't have the env prefix. It was in the django media browser template, so I added it here. I realized we were also only pushing one tag to SSM for deployment, for django. I added tag pushes for each container. 
Related error:
I also added an explicit container image name since the ecs service template reads from that first, to make sure it picks up the right image repository name.
> Fix image tag resolution for deploy stage

- cfn/configs/dev/us-east-1/config.yml
- compose/dev/django/nginx.conf
@jasonbartz suggesting using `muckrock_nginx` as the primary container in the task definition instead of django, mostly so it can use the port set by the load balancer, which for `nginx` is 80. Django needs 5000 so it got bumped and can use an explicit `port` declaration in the config.
> Change container order in config

- cfn/configs/dev/us-east-1/config.yml
- cfn/configs/prod/us-east-1/config.yml
- cfn/templates/ecs-service.template.yml
- compose/dev/django/nginx.conf
- compose/dev/django/start
- compose/local/django/Dockerfile
- compose/local/django/entrypoint
- local.yml
A few updates were needed to move this to the new account
* New namespacing pattern for SSM parameters
* New cluster (still creating, but will be called muckrock-dev/prod
* New domain/cert
I also had to tweak a lot of things as I was trying to deploy muckrock. This goes back and ensures that the local docker-compose files work and point to all the correct things, ie things in the `/compose/local/` namespace. 
It also doesn't hardcode the settings file to use, instead using an env variable `DJANGO_SETTINGS_MODULE`
> Move muckrock to new account

- cfn/configs/dev/us-east-1/config.yml
- compose/dev/django/Dockerfile.celerybeat
- compose/dev/django/Dockerfile.celeryworker
The deploy is still not completing because the celery containers don't have a healthcheck. I tested this locally by running these `CMD` declarations inside the celery containers, they both respond with a `pong`, so I think this should work since ECS will use docker's own healthchecks by default.
> Add celery container healthchecks

- cfn/configs/dev/us-east-1/config.yml
- compose/dev/django/Dockerfile.celerybeat
- compose/dev/django/Dockerfile.celeryworker
- local.yml
I had the celery healthchecks in the dockerfile but they weren't getting picked up by ECS and used.The nginx and django healthchecks are working in ECS, and they were defined in the cloudformation config, so I added the celery ones there as well. I also added them to the docker-compose file locally so I can do
And verify their health
> Move Celery Healthchecks to ECS-agent level

- cfn/configs/dev/us-east-1/config.yml
- cfn/templates/ecs-service.template.yml
Databases were switched around this week which broke the muckrock app. This adds the same `secretsmanager` get commands used in the capitol arrests admin to fetch DB creds programatically. I tested the DB connection locally and it worked.
> Update DB credentials

- compose/local/django/Dockerfile
- compose/local/django/celery/beat/start
- compose/local/django/celery/worker/start
- compose/local/django/entrypoint
- compose/local/django/start
- local.yml
On ECS, I noticed that containers were not exiting when a new deploy started, or when a healthcheck failed and the ecs-agent needed to respawn a task. This was because all of the entrypoints (django, celery) were started as child processes of shell scripts. 
When the ECS agent manages tasks, it sends a `SIGTERM` signal to the container, and only PID 1 will respond to this. Because the python entrypoints were written as child commands, they didn't have PID 1, and therefore didn't stop when sent the signal. (more here: https://aws.amazon.com/blogs/containers/graceful-shutdowns-with-ecs/). They correct way to address this is to run the entrypoint in exec form (as an array). 
I updated the docker-compose file to achieve this locally and tested by sending each container a `SIGTERM` signal and …
> Use correct docker entrypoints locally

- compose/dev/django/Dockerfile.django
Adding part of the dockerfile back in from before, it was trying to run an entrypoint that wasn't there.
> Forgot to still copy shell script into docker container before running it

- muckrock/settings/staging.py
```
RuntimeError at /
Model class silk.models.Request doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```
> add silk middleware to staging

- muckrock/agency/models/agency.py
Do not try to use squarelet to create agency users.
> Bypass squarelet when creating agency users

- compose/local/django/entrypoint
- muckrock/settings/base.py
Muckrock uses https://django-constance.readthedocs.io/en/latest/backends.html for its backend cache configuration, so I modified our settings to use redis as a backend instead of a default django one. I just followed the configuration steps in their docs and it seemed to connect fine to local redis, but will be curious to test in dev as well. I verified the elasticache connection string locally and it accepted connections fine.
> Add a redis cache config for django

- muckrock/foia/tasks.py
We are trying to figure out the delayed_submit task is silently failing, tweaking a few things including removing https://docs.celeryproject.org/en/stable/reference/celery.app.task.html#celery.app.task.Task.ignore_result from the task
> add logging and store task state in celery

- muckrock/settings/staging.py
Our emails weren't sending from celery due to an incorrect SMTP backend being set. Matching this up with the muckrock staging settings.
> fix email backend in settings

- cfn/configs/dev/us-east-1/config.yml
- muckrock/foia/constants.py
- muckrock/foia/models/request.py
- muckrock/settings/local.py
The app is still incorrectly trying to use the default django smtp backend, this is yet another attempt to override it with the mailgun backend. 
these logged out two different things:
```python
backend = settings.EMAIL_BACKEND
logger.info("email backend: %s", backend)
logger.info(settings.EMAIL_BACKEND)
```
So I am setting the backend directly and trying out a `.get()` to fetch the correct setting, and also providing the ENV var so it doesn't have to use the default value, and some more logging. 
Also, the silk profiler was slowing things to a crawl locally, @pandringa flagged this so I disabled.
> Update EMAIL_BACKEND syntax

- muckrock/foia/models/request.py
- muckrock/foia/tasks.py
The celery app receives the `foia_send_email` task:
```
[2021-04-10 15:26:13,220: INFO/MainProcess] Received task: muckrock.foia.tasks.foia_send_email[d3768e42-eb4f-494d-87d3-67b5622525de] 
```
and then...nothing. Adding some more logging, and storing the task state so I can more easily inspect whats going on with celery control (https://docs.celeryproject.org/en/latest/userguide/workers.html?highlight=revoke#dump-of-currently-executing-tasks)
> store state of foia_send_email in celery, more logging

- muckrock/foia/models/request.py
- muckrock/settings/base.py
I have now logged my way through the entire stacktrace, and noticed there was possibly a syntax error in a log message that was causing a celery task run async to fail silently (cool). Fixed that and also removed bcc'ing muckrock's diagnostics email.
> More logging tweaks

- cfn/configs/dev/us-east-1/config.yml
- muckrock/foia/models/request.py
Email finally works with a hardcoded mailgun backend, now I want it to properly read from the settings file and to use the bandit backend so we don't accidentally spam agencies.
> Remove hardcoded email backend, restore bandit email

- muckrock/assets/js/muckrock.js
- muckrock/fine_uploader/urls.py
- muckrock/fine_uploader/views.py
- muckrock/templates/lib/component/fine-uploader.html
When I started on #22, I quickly realized we'd need to refactor the uploading logic, for two reasons:
- First, we needed to move to AWS v4 signatures, because AWS has deprecated the older v2 policy signing algorithm and disabled it on new uploads (like ours)
- We also needed to adjust the behavior of the `fine-uploader` client to not hard-code the `accessKey` value, since we're now using role-based authentication with temporary, rotating access keys. The current implementation wouldn't work with our deployment setup, because there's no guarantee that the HTML template and the policy signature would come from the same container — so there was likely to be a mismatch between the access key on the client and the secret used to sign the policy.
I poked around on the [fine-uploader …
> NE-223 (pt 2): Use v4 pre-signed S3 uploads

- cfn/configs/dev/us-east-1/config.yml
- muckrock/agency/importers.py
- muckrock/communication/importers.py
- muckrock/core/storage.py
- muckrock/core/tasks.py
- muckrock/core/utils.py
- muckrock/fine_uploader/views.py
- muckrock/foia/models/composer.py
- muckrock/foia/models/request.py
- muckrock/foia/tasks.py
- muckrock/jurisdiction/importers.py
- muckrock/settings/base.py
- muckrock/settings/heroku.py
- muckrock/settings/local.py
- muckrock/task/tasks.py
Since it's a best security practice, we want to store user data in a separate (private) bucket and use query string auth to access its contents — rather than co-locate user uploads with static assets like JS/CSS/Images. Thankfully, Django has a relatively easy way to manage these two concepts separately — via the `MEDIA_URL` and `STATIC_URL` options — and we can harness the two separate `S3Boto3Storage` classes for each type to send the contents to different buckets.
This PR adds a number of new environment variables to configure options for this new bucket, including the bucket name, (optional) cloudfront distribution, and whether to use query string authentication for it. It also cleans up the handling of the existing variables, deprecating the tricky `AWS_DEBUG` variable (which had to …
> feat: Enable separate S3 bucket for user uploads

- muckrock/settings/local.py
@simongle and I wrote up an entire ticket for doing this, then realized that Squarelet already has a running mailhog instance! Since Muckrock and Squarelet run in the same docker network, all we have to do is set up the config to use SMTP and point at that instance.
https://arcpublishing.atlassian.net/browse/NE-332
- Run squarelet: `cd squarelet && docker-compose -f local.yml up`
- Run muckrock: `cd muckrock && docker-compose -f local.yml up`
- File a FOIA request, and navigate to http://dev.squarelet.com
- Ensure the email appears after 5 minutes
> NE-332: Use mailhog for local emails

- local.yml
- muckrock/core/celery.py
- muckrock/foia/tasks.py
Lob snail mail requests were silently failing, Peter found a need snippit using celery signals to log out stack traces for failed celery tasks, which helped us debug the issue locally. 
I'd like to add this enhanced logging to the dev stage so I can more info from cloudwatch on what is preventing lob from sending out mail. 
@pandringa I decided to not put the logging behind a config flag because when would we not want stack traces in cloudwatch? They will never render to the user.
> Better Celery Debugging for Lob

- compose/dev/django/Dockerfile.celerybeat
- compose/dev/django/Dockerfile.celeryworker
- compose/dev/django/Dockerfile.django
We were using a different docker image locally (python 3.8) vs on dev. On dev we saw this error when trying to generate a PDF:
`TTF Font file not found: /usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf`
I checked and locally that font file exists in the python 3.8 image.
Peter graciously pushed up a clone of the base python 3.8 image to our ECR, so this switches the dockerfiles to use that.
> Use python 3.8 image with correct font files

- compose/dev/django/Dockerfile.django
`npm ERR! enoent ENOENT: no such file or directory, open '/package.json'`
For this image I guess the path discovery for `package.json` is different? I made sure to put the npm commands after the `WORKDIR` line.
> change django image build order

- compose/dev/django/Dockerfile.django
like npm for https://github.com/WPMedia/muckrock/pull/55, the pip requirements needed to be installed after `WORKDIR` was set.
> Fix pip path also in dockerfile

- cfn/configs/dev/us-east-1/config.yml
Currently, the staging environment hijacks all outgoing email using django-email-bandit, to redirect every message to the `news-eng-qa` address. That's handy when it comes to testing out emails to agencies, but it gets a little bit annoying when it comes to internal emails: for example, the listserv gets three copies of the "Daily Digest" email every morning, or CSV download emails go to the entire group rather than people who requested them.
According to the [django-email-bandit documentation](https://github.com/caktus/django-email-bandit#installation), there's a `BANDIT_WHITELIST` settings variable which can be used to whitelist specific addresses or domains so that outgoing email can still reach them. By adding `washpost.com` to the whitelist, we're ensuring that emails directed at …
> feat: Add bandit whitelist to staging env

- cfn/configs/dev/us-east-1/config.yml
The task in ECS wasn't placing, and the only thing in dev that changed with #60 was the `service.health_check_path`. If this path doesn't return a 200 immediately, all of the containers will be stuck in pending. I want to try reverting this to see if it fixes the task placement issue, if so I'll tweak the healthcheck a bit more.
> revert healthcheck path in dev

- cfn/configs/dev/us-east-1/config.yml
- cfn/configs/prod/us-east-1/config.yml
The service wasn't being torn down properly and replaced by cloudformation because the service `muckrock-prod` already existed. This enables a feature which appends a random string to the end of the service name, making it unique so that CF can spin up and tear down separately, rather than trying to overwrite a service which may just be stuck in a bad state, which ours was.
> Hotfix: enable dynamic service name

- muckrock/settings/wapo/production.py
We want to verify email settings in production before sending to real agencies, so we need bandit to reroute email to our qa address. It was trying to do that, but unable to find bandit templates, which led us to realize that it wasn't in installed apps (which it normally shouldn't be for production) so I added it as part of the TODO block. Relevant [stacktrace](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/muckrock-prod/log-events/prod$252Fmuckrock_celeryworker$252F696cf6618b93489bafa1de0cbf5ec0c2)
> Hotfix: temp add bandit to installed apps

- muckrock/assets/js/task.js
- muckrock/settings/local.py
- muckrock/task/tasks.py
- muckrock/task/views.py
Some issues with the `boto2 -> boto3` migration (and private S3 buckets) broke the "Generate Bulk PDF" functionality on the [Snail Mail tasks page](http://dev.muckrock.com/task/snail-mail/).
The button works by requesting a route (in `task/views.py`) which generates two S3 URLs and kicks off an async task to generate a bulk PDF. While the task is running in the background, the client polls S3 with `HEAD` requests until it sees the object there, and then download the PDF for the user with a `GET` request.
This PR fixes it, with a couple of changes:
- Removing hard-coded references to the `muckrock` bucket, in favor of `settings.AWS_MEDIA_BUCKET_NAME`
- Passing presigned URLs to the client
- Creating different presaged URLs for the `GET` and `HEAD` operations (since the signatures have to …
> Fix: Bulk mail download button

- cfn/configs/dev/us-east-1/config.yml
- cfn/configs/prod/us-east-1/config.yml
- muckrock/fine_uploader/views.py
- muckrock/settings/wapo/base.py
- muckrock/settings/wapo/local.py
- muckrock/settings/wapo/production.py
- muckrock/settings/wapo/staging.py
- muckrock/templates/lib/progress_bar.html
After reviewing #71, I made a couple of tweaks to set appropriate values for the settings files and fix some of the things that were merged weirdly (particularly in `fine_uploader/views.py`).
I also added two new settings files: `wapo/base.py` (base wapo settings shared by all stages), and `wapo/local.py` (with local values we care about.) Now that all wapo settings can be isolated among those files, I moved a couple of values out of the `config.yml` environment variables and into the settings files instead. This will make bootstrapping the app much easier for future users.
From now on, to run the app locally, you'll need to set the following in your ENV:
```
DJANGO_SETTINGS_MODULE="muckrock.settings.wapo.local"
```
> Tweak settings for upstream integration

- cfn/configs/dev/us-east-1/config.yml
- cfn/configs/prod/us-east-1/config.yml
- muckrock/settings/wapo/local.py
- muckrock/settings/wapo/production.py
- muckrock/settings/wapo/staging.py
Ok I'm going to take you on a journey 🧙‍♂️ 🚶 ✨ 
1. The deploy failed.
me 👶 : 🤔 
2. The logs in [cloudwatch](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/muckrock-dev/log-events/dev$252Fmuckrock_django$252F9f00e62e17a24400b475558f0487a88b) seemed to indicate django failed the `python manage.py compress` step in the entrypoint because 
> CommandError: An error occurred during rendering /app/muckrock/templates/communication/check_list.html: 'https://wp-muckrock-dev.s3.amazonaws.com/hijack/hijack-styles.css' isn't accessible via COMPRESS_URL ('https://muckrock-devel2.s3.amazonaws.com/') and can't be compressed
👿
Wait, why is the `COMPRESS_URL` set to `https://muckrock-devel2.s3.amazonaws...`, oh thats the default in `muckrock.settings.base.py`, …
> fix: re-bind environment variables to allow app to start

- wapo-management/README.md
For security reasons, I've moved the fixture files from our public bucket to the private one.
> Readme tweaks: Update fixture file location
